# configuration file for dotnet-releaser
[msbuild]
project = "FhirParametersGenerator.sln"

[github]
user = "chgl"
repo = "FhirParametersGenerator"
version_prefix= "v"
branches = ["master"]

[coverage]
include_test_assembly = false
