<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <NoWarn>1591</NoWarn>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="Hl7.Fhir.R4" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" />
    <PackageReference
      Include="Microsoft.CodeAnalysis.Analyzers"
      PrivateAssets="all"
    />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FhirParametersGenerator.Attributes\FhirParametersGenerator.Attributes.csproj" />
    <ProjectReference Include="..\FhirParametersGenerator\FhirParametersGenerator.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference
      Include="..\FhirParametersGenerator\FhirParametersGenerator.csproj"
      OutputItemType="Analyzer"
      ReferenceOutputAssembly="false"
    />
  </ItemGroup>
</Project>
