name: ci
on:
  push:
    tags:
      - "v*"
    branches: [master]
    paths-ignore:
      - "docs/**"
      - "README.md"
  pull_request:
    branches: [master]

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      # to create releases
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Install .NET
        uses: actions/setup-dotnet@3e891b0cb619bf60e2c25674b222b8940e2c1c25 # v4.1.0
        with:
          dotnet-version: "8.0.x"

      - name: Build, Tests, Cover, Pack and Publish (on push tag)
        shell: bash
        run: |
          dotnet tool restore
          dotnet dotnet-releaser run --nuget-token "${{secrets.NUGET_TOKEN}}" --github-token "${{secrets.GITHUB_TOKEN}}" dotnet-releaser.toml

      - name: Run benchmark
        run: dotnet run -c Release --project src/FhirParametersGenerator.Benchmark

      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@d48d326b4ca9ba73ca0cd0d59f108f9e02a381c7 # v1.20.4
        with:
          name: Benchmark.Net Benchmark
          tool: "benchmarkdotnet"
          output-file-path: BenchmarkDotNet.Artifacts/results/Benchmarks-report-full-compressed.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: ${{github.event_name != 'pull_request'}}
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: "200%"
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: "@chgl"
