name: ci
on:
  push:
    tags:
      - "v*"
    branches: [master]
    paths-ignore:
      - "docs/**"
      - "README.md"
  pull_request:
    branches: [master]

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      # to create releases
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          fetch-depth: 0

      - name: Install .NET
        uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4.0.0
        with:
          dotnet-version: "10.0.x"

      - name: Build, Tests, Cover, Pack and Publish (on push tag)
        shell: bash
        run: |
          dotnet tool restore
          dotnet restore --use-lock-file
          dotnet dotnet-releaser run --nuget-token "${{secrets.NUGET_TOKEN}}" --github-token "${{secrets.GITHUB_TOKEN}}" dotnet-releaser.toml
