name: ci
on:
  push:
    tags:
      - "v*"
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "README.md"
  pull_request:
    branches:
      - master
  merge_group:
    types:
      - checks_requested

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      # to create releases
      contents: write
    name: Build, Test, Cover, Pack and Publish
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: "10.0.x"

      - name: Build, Tests, Cover, Pack and Publish (on push tag)
        shell: bash
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dotnet tool restore
          dotnet restore --locked-mode
          dotnet dotnet-releaser run --nuget-token "${NUGET_TOKEN}" --github-token "${GITHUB_TOKEN}" dotnet-releaser.toml

      - name: Run benchmark
        run: |
          dotnet run --no-restore -c Release --project src/FhirParametersGenerator.Benchmark

      - name: Discard build-time working tree changes
        run: git checkout -- .

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@52576c92bccf6ac60c8223ec7eb2565637cae9ba # v1.22.1
        with:
          name: Benchmark.Net Benchmark
          tool: "benchmarkdotnet"
          output-file-path: BenchmarkDotNet.Artifacts/results/Benchmarks-report-full-compressed.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: ${{github.event_name != 'pull_request'}}
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: "200%"
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: "@chgl"

  lint:
    uses: miracum/.github/.github/workflows/standard-lint.yaml@56f97afca6189a2fafd4e5d7cbabc6c9b83c8a85 # v1.22.4
    permissions:
      contents: read
      pull-requests: write
      issues: write
      security-events: write
      actions: read
    with:
      enable-validate-gradle-wrapper: false
      codeql-languages: '["csharp"]'
      enable-codeql: true
      enable-verify-base-image-signature: false
      dotnet-version: "10.0.x"
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
