name: Check Spelling using cspell
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  spell-check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - run: npx cspell@6.1.2 lint --gitignore "**/*"
